#!/usr/bin/Rscript --vanilla
## R script for plotting KBA runs from CSV generated by _output.py

library(ggplot2)
library(stringr)
library(lattice)
library(reshape2)
library(scales)

options(echo=TRUE) # if you want see commands in output file
args <- commandArgs(trailingOnly = TRUE)
#print(args)
#trailingOnly=TRUE means that only your arguments are returned, check:
#print(commandsArgs(trailingOnly=FALSE))

## need to make args work to run this on many many files
file_v  <- args[1]  #"ccr-all-entities-vital-macroavg-cutoff-step-size-1-run-overview-maxF.csv"
file_vu <- args[2]  #"ccr-all-entities-vital+useful-macroavg-cutoff-step-size-1-run-overview-maxF.csv"

#print(args[1])
#print(file_v)

## Max wrote this and the next function
makeplot_F <- function(myfile, name, ylabel){
	cs <- read.csv(myfile)

	cs.sort <- with(cs, reorder(team_id, macro_average_F, max))

	myplot <- dotplot(macro_average_F~cs.sort, data=cs, ylim=c(-.05,1.0), main=name, scales=list(cex=0.6, rot=37), ylab=ylabel, asp=0.7, panel = function(x, y, ...) {
            	panel.dotplot(x, y, ...)
            	panel.text(as.numeric(cs.sort), cs$macro_average_F,
                       	labels = '', #as.character(cs$run),
                       	pos = 4,cex=.6)})
    return(myplot)
}

v_F  = makeplot_F(file_v,  '', expression(max(F[1](avg(P),avg(R)))))
vu_F = makeplot_F(file_vu, '', expression(max(F[1](avg(P),avg(R)))))

makeplot_SU <- function(myfile, name, ylabel){
	cs <- read.csv(myfile)

	cs.sort <- with(cs, reorder(team_id, macro_average_SU, max))

        ## should convert this to a log plot on vertical axis
        
	myplot <- dotplot(log(macro_average_SU)~cs.sort, data=cs, ylim=c(-3.0, 3.0), main=name, scales=list(cex=0.6, rot=37), ylab=ylabel, asp=0.7, panel = function(x, y, ...) {
            	panel.dotplot(x, y, ...)
            	panel.text(as.numeric(cs.sort), cs$macro_average_SU,
                       	labels = '', #as.character(cs$run),
                       	pos = 4,cex=.6)})
    return(myplot)
}

## read the macro_average_SU column out of the CSV
v_SU  = makeplot_SU(file_v,  '', expression(max(log(SU))))
vu_SU = makeplot_SU(file_vu, '', expression(max(log(SU))))

makeplot_PRF <- function(myfile, name) {
  #% A Precision/Recall/F plot
  z <- matrix(nrow=100, ncol=100)
  p <- seq(0, 1, length=100)
  r <- seq(0, 1, length=100)
  beta = 1
  for (pi in 0:100)
    for (ri in 0:100)
      z[pi,ri] <- ((1 + beta) * p[pi] * r[ri]) / (beta * p[pi] + r[ri])

  cs <- read.csv(myfile)

  ## from Ian...
  #contour(r,p,z,ylab="Precision", xlab="Recall", main="F score")

  ## this is from Ian, but hacked by jrf to ref "cs"... and I've never seen it work
  #points(cs$R_at_best_F, cs$P_at_best_F)

  ## ggplot2 needs a dataframe, so convert it and rescale the x,y data
  ## to be between zero and one 
  ### this used to say value.name="f" but that was failing
  df <- melt(z, varnames=c("p", "r"), name="f")
  df <- transform(df, p=rescale(p, to=c(0,1)))
  df <- transform(df, r=rescale(r, to=c(0,1)))

  ## http://www.burns-stat.com/pages/Tutor/R_inferno.pdf
  #print(df)
  
  ## this combines two plots, and returns it
    g <- ggplot(main=name) +
      opts(title = name) +
      stat_contour(data=df, aes(x=p, y=r, z=value)) + 
          geom_point(data=cs, aes(x=macro_average_P, y=macro_average_R, color=factor(team_id), shape=factor(team_id))) +
              scale_shape_manual(values=1:20)

  return(g)
}
v_PRF  = makeplot_PRF(file_v,  args[1])
vu_PRF = makeplot_PRF(file_vu, args[2])

pdf(args[3])

## why don't these appear in the same page as the four below
print(v_PRF,   split=c(1,1,2,3), more=TRUE)
print(vu_PRF,  split=c(2,1,2,3), more=TRUE)

## these appear "correctly"
print(v_SU,  split=c(1,2,2,3), more=TRUE)
print(vu_SU, split=c(2,2,2,3), more=TRUE)
print(v_F,  split=c(1,3,2,3), more=TRUE)
print(vu_F, split=c(2,3,2,3))
dev.off()
